Revocation Handle Comm
IBM/idemix pull request #26
Opened 2023-02-24 12:17 UTC by adecaro

This PR adds commitment functionality to the revocation handle attribute. This is achieved through the following changes:

- Introduction of new revocation handle types pertaining to signatures, signature types, and signature options
- More generalized attribute functionality to handle both enrollment id and revocation handle commitment schemes
- Addition of ability to generate a pseudonym of a revocation handle (commitment)
- Addition of ability to generate a signature containing both an enrollment id pseudonym and a revocation handle pseudonym
- Functionality for auditing and verifying the new signature type

PR motivation: https://github.com/IBM/idemix/issues/21

2023-03-02 10:29 UTC, ale-linux requested changes
Fantastic, thanks Angelo! Just 2 missing tests and we're good to merge!

2023-03-02 10:29 UTC, ale-linux commented on bccsp/schemes/dlog/bridge/signaturescheme.go
> +	case bccsp.AuditExpectEidNymRhNym:
untested

2023-03-02 10:29 UTC, ale-linux commented on bccsp/schemes/dlog/bridge/signaturescheme.go
> +	case bccsp.AuditExpectEidNymRhNym:
untested

2023-04-18 06:56 UTC, adecaro commented on bccsp/schemes/dlog/bridge/signaturescheme.go
> +	case bccsp.AuditExpectEidNymRhNym:
test added

2023-04-18 06:56 UTC, adecaro commented on bccsp/schemes/dlog/bridge/signaturescheme.go
> +	case bccsp.AuditExpectEidNymRhNym:
test added

2023-04-18 06:56 UTC, adecaro commented
Hi @ale-linux , I have extended the test to cover the cases you pointed to. Please, have another look :)

2023-04-18 08:48 UTC, ale-linux approved these changes

2023-04-18 08:48 UTC, merged